### ISSUE TITLE
TypeError: Accumulator_3D() takes 2 positional arguments but 4 were given

### ISSUE THREAD

**Issue by andreazuna89** [aaronWool/rcvpose#1]
Hi,
thanks for the great work. I am testing RCVPose but got the following error:

center_mm_s = Accumulator_3D(xyz, xyz_load_transformed, radial_list, pixel_coor)
TypeError: Accumulator_3D() takes 2 positional arguments but 4 were given

The function is defined for two inputs as arguments. Can you help here?

Best

**Comment by aaronWool** [comment]
Hi,
Please try now. It should run fine.
